C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-g-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-b-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-k-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-v-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-n-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-w-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-a-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-l-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-s-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-j-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-d-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-r-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-h-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-f-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-t-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-u-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-e-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-x-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-i-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-p-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-y-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-z-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-q-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-m-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-o-8x13.bmp
C:\Users\MArkovka\Desktop\bmp_to_ePaper_MONO pt-mono-bold-c-8x13.bmp
